export const SOCKET_EVENTS = Object.freeze({
  CONNECTED: 'CONNECTED',
  SUBSCRIBE_QUEUE: 'SUBSCRIBE_QUEUE',
  SUBSCRIPTION_CONFIRMED: 'SUBSCRIPTION_CONFIRMED',
  SUBSCRIPTION_DENIED: 'SUBSCRIPTION_DENIED',
  QUEUE_UPDATED: 'QUEUE_UPDATED',
  TOKEN_CANCELLED: 'TOKEN_CANCELLED',
  NEXT_USER_CALLED: 'NEXT_USER_CALLED',
  QUEUE_AUTO_ADVANCED: 'QUEUE_AUTO_ADVANCED',
  NEXT_USER_AUTOMATICALLY_CALLED: 'NEXT_USER_AUTOMATICALLY_CALLED',
  COUNTER_STATUS_CHANGED: 'COUNTER_STATUS_CHANGED',
  PREDICTION_UPDATED: 'PREDICTION_UPDATED',
  NOTIFICATION_RECEIVED: 'NOTIFICATION_RECEIVED',
  MANAGER_LOCATION_UPDATED: 'MANAGER_LOCATION_UPDATED',
})

export const rooms = Object.freeze({
  user: (userId) => `user:${userId}`,
  location: (locationId) => `location:${locationId}`,
  managerBranch: (locationId) => `manager-branch:${locationId}`,
})
