import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { formatDistanceToNow } from 'date-fns'
import { Activity, AlertTriangle, BarChart3, BellRing, CheckCircle2, Coffee, DoorClosed, Play, Settings2, TicketPlus, Users, XCircle } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useLocation, useNavigate } from 'react-router-dom'
import { InitialLoadingSkeleton } from '../../../components/feedback/InitialLoadingSkeleton'
import { NetworkErrorFallback } from '../../../components/feedback/NetworkErrorFallback'
import { Button } from '../../../components/ui/Button'
import { Input } from '../../../components/ui/Input'
import { StatusBadge } from '../../../components/ui/StatusBadge'
import { managerApi, type Counter } from '../api/managerApi'
import { CounterControl } from '../../manager/components/CounterControl'
import { MetricCard } from '../components/MetricCard'
import { PageHeader } from '../components/PageHeader'

type ManagerTab = 'counters' | 'queue' | 'settings' | 'analytics' | 'alerts'
const tabs: Array<{ id: ManagerTab; label: string; path: string; icon: typeof Activity }> = [
  { id: 'counters', label: 'Counter desk', path: '/app/manager/counters', icon: Activity }, { id: 'queue', label: 'Live queue', path: '/app/manager/queue', icon: Users }, { id: 'settings', label: 'Branch settings', path: '/app/manager/settings', icon: Settings2 }, { id: 'analytics', label: 'Local analytics', path: '/app/manager/analytics', icon: BarChart3 }, { id: 'alerts', label: 'Alerts', path: '/app/manager/alerts', icon: BellRing },
]

export function ManagerDashboard() {
  const location = useLocation(); const navigate = useNavigate(); const tab = tabs.find((item) => item.path === location.pathname)?.id ?? 'counters'
  return <><PageHeader eyebrow="Manager workspace" title="Branch operations" description="Real-time controls and insights restricted to your assigned branch." /><nav className="mb-6 flex gap-2 overflow-x-auto pb-2" aria-label="Manager features">{tabs.map(({ id, label, path, icon: Icon }) => <button key={id} onClick={() => navigate(path)} aria-pressed={tab === id} className={`inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-4 text-sm font-bold ${tab === id ? 'bg-navy text-white' : 'border border-slate-200 bg-white text-slate-600'}`}><Icon size={17} />{label}</button>)}</nav>{tab === 'counters' && <CounterDesk />}{tab === 'queue' && <QueueConsole />}{tab === 'settings' && <BranchSettings />}{tab === 'analytics' && <LocalAnalytics />}{tab === 'alerts' && <ManagerAlerts />}</>
}

function CounterDesk() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['manager-counters'], queryFn: managerApi.getCounters, refetchInterval: 5_000 })
  const statusMutation = useMutation({ mutationFn: ({ id, status }: { id: string; status: Counter['status'] }) => managerApi.updateCounterStatus(id, status), onSuccess: () => { client.invalidateQueries({ queryKey: ['manager-counters'] }); client.invalidateQueries({ queryKey: ['prediction-core'] }) } })
  const nextMutation = useMutation({ mutationFn: managerApi.callNext, onSuccess: () => { client.invalidateQueries({ queryKey: ['manager-queue'] }); client.invalidateQueries({ queryKey: ['manager-alerts'] }); client.invalidateQueries({ queryKey: ['prediction-core'] }) } })
  if (query.isLoading) return <InitialLoadingSkeleton />; if (query.isError) return <NetworkErrorFallback onRetry={() => query.refetch()} />
  return <section><div className="mb-5"><h2 className="text-xl font-bold">Real-Time Counter Control Desk</h2><p className="text-sm text-slate-500">{query.data?.location.location}</p></div><CounterControl locationId={query.data?.location._id} />{(statusMutation.isError || nextMutation.isError) && <ManagerError error={statusMutation.error || nextMutation.error} />}<div className="grid gap-4 lg:grid-cols-3">{query.data?.counters.map((counter) => <article key={counter._id} className="card p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-ocean">Service window</p><h3 className="mt-1 text-xl font-bold">{counter.name}</h3></div><StatusBadge tone={counter.status === 'Active' ? 'success' : counter.status === 'Break' ? 'warning' : 'neutral'}>{counter.status}</StatusBadge></div><div className="mt-5 grid grid-cols-3 gap-2">{(['Active', 'Break', 'Closed'] as const).map((status) => <button key={status} onClick={() => statusMutation.mutate({ id: counter._id, status })} className={`rounded-lg border px-2 py-2 text-xs font-bold ${counter.status === status ? 'border-navy bg-navy text-white' : 'border-slate-200 bg-white'}`}>{status === 'Active' ? <Play size={14} className="mx-auto mb-1" /> : status === 'Break' ? <Coffee size={14} className="mx-auto mb-1" /> : <DoorClosed size={14} className="mx-auto mb-1" />}{status}</button>)}</div><Button className="mt-4 w-full" disabled={counter.status !== 'Active' || nextMutation.isPending} onClick={() => nextMutation.mutate(counter._id)}>Call next customer</Button></article>)}</div>{nextMutation.data && <p role="status" className="mt-5 rounded-xl bg-emerald-50 p-4 font-bold text-emerald-800">Now serving {nextMutation.data.code}</p>}</section>
}

function QueueConsole() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['manager-queue'], queryFn: managerApi.getLiveQueue, refetchInterval: 4_000 })
  const walkIn = useMutation({ mutationFn: managerApi.createWalkIn, onSuccess: () => client.invalidateQueries({ queryKey: ['manager-queue'] }) }); const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: 'completed' | 'cancelled' }) => managerApi.updateTokenStatus(id, status), onSuccess: () => client.invalidateQueries({ queryKey: ['manager-queue'] }) })
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); walkIn.mutate({ service: String(data.get('service')), phone: String(data.get('phone')) }, { onSuccess: () => form.reset() }) }
  if (query.isLoading) return <InitialLoadingSkeleton />; if (query.isError) return <NetworkErrorFallback onRetry={() => query.refetch()} />
  return <section><div className="grid gap-6 xl:grid-cols-[1fr_340px]"><div className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="text-xl font-bold">Live Queue Oversight</h2><p className="text-sm text-slate-500">Chronological waiting and serving tokens across every service at your assigned branch.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Token</th><th className="p-4">Service</th><th className="p-4">Status</th><th className="p-4">Waiting</th><th className="p-4">Actions</th></tr></thead><tbody>{query.data?.tokens.map((token) => <tr key={token._id} className="border-t border-slate-100"><td className="p-4"><strong>{token.code}</strong>{token.priority === 'high' && <span className="ml-2 rounded-full bg-red-50 px-2 py-1 text-xs font-bold text-red-700">Priority</span>}</td><td className="p-4 text-sm">{token.service}</td><td className="p-4"><StatusBadge tone={token.status === 'serving' ? 'info' : 'warning'}>{token.status}</StatusBadge></td><td className="p-4 text-sm text-slate-500">{formatDistanceToNow(new Date(token.createdAt))}</td><td className="p-4"><div className="flex gap-2">{token.status === 'serving' && <button onClick={() => update.mutate({ id: token._id, status: 'completed' })} className="rounded-lg bg-emerald-50 p-2 text-emerald-700" aria-label={`Complete ${token.code}`}><CheckCircle2 size={17} /></button>}<button onClick={() => update.mutate({ id: token._id, status: 'cancelled' })} className="rounded-lg bg-red-50 p-2 text-red-700" aria-label={`Cancel ${token.code}`}><XCircle size={17} /></button></div></td></tr>)}</tbody></table>{!query.data?.tokens.length && <p className="p-8 text-center text-slate-500">The live queue is empty.</p>}</div></div><form onSubmit={submit} className="card h-fit space-y-4 p-5"><div><TicketPlus className="text-ocean" /><h2 className="mt-2 font-bold">Emergency/VIP walk-in</h2><p className="text-sm text-slate-500">Creates a high-priority token.</p></div><label className="block text-sm font-bold">Service required<select required name="service" className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal"><option value="">Select a branch service</option>{query.data?.services.map((item) => <option key={item.locationId} value={item.service}>{item.service}</option>)}</select></label><Input required name="phone" label="Phone" pattern="\+?[0-9]{10,14}" /><Button className="w-full" disabled={walkIn.isPending}>Create priority token</Button>{(walkIn.isError || update.isError) && <ManagerError error={walkIn.error || update.error} />}</form></div></section>
}

function BranchSettings() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['manager-settings'], queryFn: managerApi.getLocationSettings }); const mutation = useMutation({ mutationFn: managerApi.updateLocationSettings, onSuccess: () => client.invalidateQueries({ queryKey: ['manager-settings'] }) }); const [hours, setHours] = useState({ openTime: '09:00', closeTime: '17:00', defaultServiceMinutes: '15' })
  useEffect(() => { if (query.data) setHours({ openTime: query.data.businessHours?.openTime || '09:00', closeTime: query.data.businessHours?.closeTime || '17:00', defaultServiceMinutes: String(query.data.defaultServiceMinutes || 15) }) }, [query.data])
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); mutation.mutate(data) }
  if (query.isLoading) return <InitialLoadingSkeleton />; if (query.isError) return <NetworkErrorFallback onRetry={() => query.refetch()} />
  return <section className="card p-6"><h2 className="text-xl font-bold">Branch Profile & Metadata</h2><p className="mt-1 text-sm text-slate-500">{query.data?.location} · {query.data?.category}</p><form onSubmit={submit} className="mt-6 grid gap-5 md:grid-cols-2"><Input name="openTime" label="Opening time" type="time" value={hours.openTime} onChange={(event) => setHours({ ...hours, openTime: event.target.value })} /><Input name="closeTime" label="Closing time" type="time" value={hours.closeTime} onChange={(event) => setHours({ ...hours, closeTime: event.target.value })} /><Input name="defaultServiceMinutes" label="Default service duration (minutes)" type="number" min={1} max={240} value={hours.defaultServiceMinutes} onChange={(event) => setHours({ ...hours, defaultServiceMinutes: event.target.value })} /><label className="text-sm font-bold">Schedule or desk image<input name="scheduleImage" type="file" accept="image/png,image/jpeg,image/webp" className="mt-2 block w-full rounded-xl border border-dashed border-slate-300 p-3 text-sm" /></label><Button className="md:col-span-2" disabled={mutation.isPending}>Save branch settings</Button>{mutation.isError && <div className="md:col-span-2"><ManagerError error={mutation.error} /></div>}{mutation.isSuccess && <p className="md:col-span-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">Branch settings updated.</p>}</form></section>
}

function LocalAnalytics() {
  const query = useQuery({ queryKey: ['manager-analytics'], queryFn: managerApi.getAnalytics, refetchInterval: 30_000 }); if (query.isLoading) return <InitialLoadingSkeleton />; if (query.isError) return <NetworkErrorFallback onRetry={() => query.refetch()} />
  const chart = query.data?.hourlyVolume.map((row) => ({ ...row, label: `${String(row.hour).padStart(2, '0')}:00` })) ?? []
  return <section><h2 className="mb-4 text-xl font-bold">Localized Analytics Dashboard</h2><div className="grid gap-4 md:grid-cols-3"><MetricCard label="Completed today" value={String(query.data?.completed ?? 0)} detail="Successfully served" accent /><MetricCard label="Abandoned today" value={String(query.data?.cancelled ?? 0)} detail="Cancelled or no-show" /><MetricCard label="Active counter samples" value={String(query.data?.counterSpeed.length ?? 0)} detail="Processing speed tracked" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_380px]"><section className="card p-5"><h3 className="mb-4 font-bold">Hourly customer bottlenecks</h3>{chart.length ? <ResponsiveContainer width="100%" height={300}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="customers" fill="#176b87" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer> : <p className="grid h-[300px] place-items-center text-sm text-slate-500">No token volume recorded today.</p>}</section><section className="card p-5"><h3 className="font-bold">Average speed by counter</h3><div className="mt-4 space-y-3">{query.data?.counterSpeed.map((row) => <div key={row.counterId} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between"><strong>{row.counterName}</strong><span>{row.averageProcessingMinutes} min</span></div><p className="text-xs text-slate-500">{row.completed} completed</p></div>)}{!query.data?.counterSpeed.length && <p className="text-sm text-slate-500">Complete tokens to calculate speed.</p>}</div></section></div></section>
}

function ManagerAlerts() {
  const query = useQuery({ queryKey: ['manager-alerts'], queryFn: managerApi.getNotifications, refetchInterval: 5_000 }); if (query.isLoading) return <InitialLoadingSkeleton />; if (query.isError) return <NetworkErrorFallback onRetry={() => query.refetch()} />
  return <section><div className="mb-5"><h2 className="text-xl font-bold">Operational Manager Notifications</h2><p className="text-sm text-slate-500">Live queue threshold and stale-token monitoring every five seconds.</p></div><div className="grid gap-4 md:grid-cols-2"><MetricCard label="Waiting now" value={String(query.data?.waiting ?? 0)} detail="Surge threshold: over 20" accent /><MetricCard label="Service baseline" value={`${query.data?.baselineMinutes ?? 0} min`} detail="Stale threshold: twice baseline" /></div><div className="mt-6 space-y-3">{query.data?.alerts.map((alert) => <article key={alert.id} className={`card flex gap-3 p-5 ${alert.severity === 'critical' ? 'border-red-200 bg-red-50' : 'border-amber-200 bg-amber-50'}`}><AlertTriangle className={alert.severity === 'critical' ? 'text-red-600' : 'text-amber-600'} /><div><h3 className="font-bold">{alert.title}</h3><p className="text-sm text-slate-600">{alert.message}</p></div></article>)}{!query.data?.alerts.length && <article className="card p-8 text-center"><CheckCircle2 className="mx-auto text-emerald-600" /><h3 className="mt-3 font-bold">Operations are healthy</h3><p className="text-sm text-slate-500">No surge or stale-token warnings.</p></article>}</div></section>
}

function ManagerError({ error }: { error: unknown }) { const message = typeof error === 'object' && error && 'message' in error && typeof error.message === 'string' ? error.message : 'The manager operation failed.'; return <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</p> }
